// <auto-generated />
using System;
using DataBase.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataBase.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230615162549_NewDataBase15")]
    partial class NewDataBase15
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataBase.DataContext.Tables.DBUser", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea")
                        .HasColumnName("passwordhash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("passwordsalt");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.HistoricalDataItems", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric")
                        .HasColumnName("high");

                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("open");

                    b.Property<int>("TimeStamp")
                        .HasColumnType("integer")
                        .HasColumnName("timeStamp");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("ItemId");

                    b.HasIndex("ListId");

                    b.ToTable("historiacalDataItems");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.HistoricalDataList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListId"));

                    b.Property<long>("Datasize")
                        .HasColumnType("bigint")
                        .HasColumnName("datasize");

                    b.Property<DateTime>("TimeStampEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestampend");

                    b.Property<DateTime>("TimeStampStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestampstart");

                    b.HasKey("ListId");

                    b.ToTable("Historicaldatalist");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.HystoriaclCryptoDataList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListId"));

                    b.Property<long>("DataSize")
                        .HasColumnType("bigint")
                        .HasColumnName("DataSize");

                    b.Property<DateTime>("TimeStampEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TimestampEnd");

                    b.Property<DateTime>("TimeStampStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TimestampStart");

                    b.HasKey("ListId");

                    b.ToTable("HystoricalCryptoDataList");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.HystoricalCryptoDataItems", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("DataType");

                    b.Property<DateTime>("Endtime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndTime");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric")
                        .HasColumnName("High");

                    b.Property<bool>("IsFillForward")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFillForward");

                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric")
                        .HasColumnName("Low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("Open");

                    b.Property<TimeSpan>("Period")
                        .HasColumnType("interval")
                        .HasColumnName("Period");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("Pric");

                    b.Property<string>("Symbolstring")
                        .HasColumnType("text")
                        .HasColumnName("Symbol");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Time");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("Value");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("Volume");

                    b.HasKey("id");

                    b.HasIndex("ListId");

                    b.ToTable("HystoricalCryptoDataItems");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.TickerDayDataItems", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<decimal>("Ask")
                        .HasColumnType("numeric")
                        .HasColumnName("lowest_sell_order");

                    b.Property<decimal>("Bid")
                        .HasColumnType("numeric")
                        .HasColumnName("highest_buy_order");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("highestPrice");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("lastprice");

                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("lowestPrice");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("first_price_of_day");

                    b.Property<decimal>("Open24")
                        .HasColumnType("numeric")
                        .HasColumnName("open_24");

                    b.Property<string>("Pair")
                        .HasColumnType("text")
                        .HasColumnName("pair");

                    b.Property<decimal>("PercentChange24")
                        .HasColumnType("numeric")
                        .HasColumnName("percent_change_24");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("VWap")
                        .HasColumnType("numeric")
                        .HasColumnName("volume_weighted_average_price");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("ItemId");

                    b.HasIndex("ListId");

                    b.ToTable("tickerDataItems");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.TickerDayDataList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListId"));

                    b.Property<long>("DataSize")
                        .HasColumnType("bigint")
                        .HasColumnName("datasize");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("ListId");

                    b.ToTable("tickerDataList");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.TickerHourDataItems", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<decimal>("Ask")
                        .HasColumnType("numeric")
                        .HasColumnName("lowest_sell_order");

                    b.Property<decimal>("Bid")
                        .HasColumnType("numeric")
                        .HasColumnName("highest_buy_order");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("highestPrice");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("lastprice");

                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("lowestPrice");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("first_price_of_day");

                    b.Property<decimal>("Open24")
                        .HasColumnType("numeric")
                        .HasColumnName("open_24");

                    b.Property<string>("Pair")
                        .HasColumnType("text")
                        .HasColumnName("pair");

                    b.Property<decimal>("PercentChange24")
                        .HasColumnType("numeric")
                        .HasColumnName("percent_change_24");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("VWap")
                        .HasColumnType("numeric")
                        .HasColumnName("volume_weighted_average_price");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("ItemId");

                    b.HasIndex("ListId");

                    b.ToTable("tickerHourDataItems");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.TickerHourDataList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListId"));

                    b.Property<long>("DataSize")
                        .HasColumnType("bigint")
                        .HasColumnName("datasize");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("ListId");

                    b.ToTable("tickerHourDataList");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.HistoricalDataItems", b =>
                {
                    b.HasOne("DataBase.DataContext.Tables.HistoricalDataList", "List")
                        .WithMany("DataSets")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.HystoricalCryptoDataItems", b =>
                {
                    b.HasOne("DataBase.DataContext.Tables.HystoriaclCryptoDataList", "List")
                        .WithMany("Datasets")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.TickerDayDataItems", b =>
                {
                    b.HasOne("DataBase.DataContext.Tables.TickerDayDataList", "List")
                        .WithMany("TickerDayDataItems")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.TickerHourDataItems", b =>
                {
                    b.HasOne("DataBase.DataContext.Tables.TickerHourDataList", "List")
                        .WithMany("TickerHourDataItems")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.HistoricalDataList", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.HystoriaclCryptoDataList", b =>
                {
                    b.Navigation("Datasets");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.TickerDayDataList", b =>
                {
                    b.Navigation("TickerDayDataItems");
                });

            modelBuilder.Entity("DataBase.DataContext.Tables.TickerHourDataList", b =>
                {
                    b.Navigation("TickerHourDataItems");
                });
#pragma warning restore 612, 618
        }
    }
}
